# @format

spring:
    config:
        activate:
            on-profile: prod

server:
    address: 0.0.0.0
    port: 6443
    servlet:
        multipart:
            enabled: true
            max-file-size: 200MB
            max-request-size: 500MB
            # location: /opt/_was_file_and_logs/_files/_tomcat_mobile
